#!/usr/bin/env python3
"""Extract Databricks Lakeview .lvdash.json dashboards into graphify-friendly sidecars.

graphify detects .lvdash.json in the manifest but generic JSON AST extraction
produces no useful nodes. This script emits, next to each dashboard file:

    <name>.lvdash.sql   datasets[].queryLines joined -> SQL AST (table references)
    <name>.lvdash.md    dashboard summary for semantic extraction

Stdlib only. Pair with ipynb-graphify via /databricks-graphify.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

IGNORE_DIRS = {
    ".git", ".hg", ".svn", ".ipynb_checkpoints", "node_modules",
    "graphify-out", ".venv", "venv", "env", "__pycache__", ".cursor",
    ".mypy_cache", ".pytest_cache", "dist", "build", ".tox",
}

_TABLE_RE = re.compile(
    r"(?i)\b(?:from|join)\s+([a-z_][\w$]*(?:\.[a-z_][\w$]*)+)",
)


def lvdash_stem(path: Path) -> str:
    name = path.name
    if name.lower().endswith(".lvdash.json"):
        return name[: -len(".lvdash.json")]
    return path.stem


def _query_lines_to_sql(lines) -> str:
    if isinstance(lines, str):
        return lines.replace("\r\n", "\n").strip()
    if isinstance(lines, list):
        return "".join(str(x) for x in lines).replace("\r\n", "\n").strip()
    return ""


def _tables_in_sql(sql: str) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for m in _TABLE_RE.finditer(sql):
        t = m.group(1).lower()
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out


def convert_lvdash(path: Path, root: Path, outdir: Path | None) -> dict:
    try:
        doc = json.loads(path.read_text(encoding="utf-8", errors="ignore"))
    except (json.JSONDecodeError, OSError) as exc:
        return {"dashboard": str(path), "error": str(exc), "written": []}

    if not isinstance(doc, dict):
        return {"dashboard": str(path), "error": "not a JSON object", "written": []}

    try:
        rel = path.relative_to(root)
    except ValueError:
        rel = Path(path.name)

    stem = lvdash_stem(path)
    datasets = doc.get("datasets") or []
    pages = doc.get("pages") or []

    sql_chunks: list[str] = []
    md_rows: list[str] = []
    all_tables: set[str] = set()
    dataset_count = 0

    if isinstance(datasets, list):
        for ds in datasets:
            if not isinstance(ds, dict):
                continue
            query = _query_lines_to_sql(ds.get("queryLines"))
            if not query:
                continue
            dataset_count += 1
            name = ds.get("name") or f"dataset_{dataset_count}"
            display = ds.get("displayName") or name
            tables = _tables_in_sql(query)
            all_tables.update(tables)
            sql_chunks.append(
                f"-- %% dataset {display} [{name}]\n{query.rstrip()}\n"
            )
            table_cell = ", ".join(f"`{t}`" for t in tables) if tables else "—"
            md_rows.append(f"| {display} | `{name}` | {table_cell} |")

    page_names: list[str] = []
    if isinstance(pages, list):
        for page in pages:
            if isinstance(page, dict) and page.get("displayName"):
                page_names.append(str(page["displayName"]))

    if outdir is not None:
        out_parent = (outdir / rel).parent
        out_parent.mkdir(parents=True, exist_ok=True)
        sidecar_dir = out_parent
    else:
        sidecar_dir = path.parent

    written: list[str] = []
    if sql_chunks:
        sql_path = sidecar_dir / f"{stem}.lvdash.sql"
        header = f"-- Generated by databricks-graphify from {rel} — do not edit.\n"
        header += f"-- Lakeview dashboard: {stem}\n"
        if all_tables:
            header += "-- Tables: " + ", ".join(sorted(all_tables)) + "\n"
        sql_path.write_text(header + "\n" + "\n".join(sql_chunks), encoding="utf-8")
        written.append(str(sql_path))

    md_path = sidecar_dir / f"{stem}.lvdash.md"
    md_lines = [
        f"# {stem} (Databricks Lakeview dashboard)",
        "",
        f"Source: `{rel.as_posix()}`",
        "",
        "Databricks AI/BI dashboard definition (`.lvdash.json`). Sidecar generated by "
        "`databricks-graphify` so graphify can index dataset queries and gold-table dependencies.",
        "",
    ]
    if all_tables:
        md_lines.extend([
            "## Consumes",
            "",
            *(f"- `{t}`" for t in sorted(all_tables)),
            "",
        ])
    if md_rows:
        md_lines.extend([
            "## Datasets",
            "",
            "| displayName | id | tables |",
            "|-------------|-----|--------|",
            *md_rows,
            "",
        ])
    if page_names:
        md_lines.extend(["## Pages", "", *(f"- {p}" for p in page_names), ""])

    if dataset_count or page_names or all_tables:
        md_path.write_text("\n".join(md_lines).rstrip() + "\n", encoding="utf-8")
        written.append(str(md_path))

    return {
        "dashboard": str(path),
        "datasets": dataset_count,
        "pages": len(page_names),
        "tables": sorted(all_tables),
        "written": written,
    }


def find_lvdash(root: Path):
    for p in root.rglob("*.lvdash.json"):
        if any(part in IGNORE_DIRS for part in p.parts):
            continue
        yield p


def clean(root: Path) -> list[str]:
    removed: list[str] = []
    for pattern in ("*.lvdash.sql", "*.lvdash.md"):
        for p in root.rglob(pattern):
            if any(part in IGNORE_DIRS for part in p.parts):
                continue
            try:
                p.unlink()
                removed.append(str(p))
            except OSError:
                pass
    return removed


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Extract .lvdash.json dashboards into graphify-friendly sidecars."
    )
    ap.add_argument("path", nargs="?", default=".", help="File or directory (default: cwd).")
    ap.add_argument("--outdir", default=None, help="Mirror sidecars under this directory.")
    ap.add_argument("--clean", action="store_true", help="Remove *.lvdash.sql/md sidecars.")
    args = ap.parse_args(argv)

    root = Path(args.path).resolve()
    if not root.exists():
        print(json.dumps({"error": f"path not found: {root}"}))
        return 1

    if args.clean:
        base = root if root.is_dir() else root.parent
        removed = clean(base)
        print(json.dumps({"cleaned": len(removed), "files": removed}, indent=2))
        return 0

    outdir = Path(args.outdir).resolve() if args.outdir else None
    scan_root = root if root.is_dir() else root.parent
    paths = (
        [root]
        if root.is_file() and root.name.lower().endswith(".lvdash.json")
        else list(find_lvdash(root))
    )

    results = [convert_lvdash(p, scan_root, outdir) for p in paths]
    written = [w for r in results for w in r.get("written", [])]
    errors = [r for r in results if r.get("error")]
    tables = sorted({t for r in results for t in r.get("tables", [])})

    summary = {
        "dashboards": len(paths),
        "sidecars_written": len(written),
        "unique_tables": tables,
        "errors": [{"dashboard": e["dashboard"], "error": e["error"]} for e in errors],
        "results": results,
    }
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
