#!/usr/bin/env python3
"""Split Jupyter / Databricks .ipynb notebooks into per-language sidecar files
so stock graphify can index them.

graphify ignores .ipynb (it is in neither CODE_EXTENSIONS nor DOC_EXTENSIONS).
This script emits, next to each notebook, the cells re-bucketed by language:

    <stem>.ipynb.py     code cells           -> tree-sitter AST extraction (free)
    <stem>.ipynb.md     markdown / %md cells -> semantic extraction
    <stem>.ipynb.sql    %sql cells           -> SQL AST extraction
    <stem>.ipynb.sh     %sh / %bash cells    -> shell AST extraction
    <stem>.ipynb.scala  %scala cells
    <stem>.ipynb.r      %r cells

Only buckets that have content are written. Run /graphify on the same root
afterwards and it will pick the sidecars up. Stdlib only -- no nbconvert.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

IGNORE_DIRS = {
    ".git", ".hg", ".svn", ".ipynb_checkpoints", "node_modules",
    "graphify-out", ".venv", "venv", "env", "__pycache__", ".cursor",
    ".mypy_cache", ".pytest_cache", "dist", "build", ".tox",
}

# Whole-cell / first-line magic -> bucket. .py/.md/.sql/.sh/.scala/.r are all
# extensions graphify already understands.
MAGIC_TO_BUCKET = {
    "md": "md", "markdown": "md",
    "sql": "sql",
    "sh": "sh", "bash": "sh",
    "scala": "scala",
    "r": "r",
    "python": "py", "python3": "py", "pyspark": "py",
}

BUCKET_EXT = {
    "py": "py", "md": "md", "sql": "sql",
    "sh": "sh", "scala": "scala", "r": "r",
}

# Comment leaders so a generated file announces its provenance in its own syntax.
COMMENT = {
    "py": "# {}", "sh": "# {}", "r": "# {}",
    "sql": "-- {}", "scala": "// {}",
    "md": "<!-- {} -->",
}

_MAGIC_RE = re.compile(r"^\s*%{1,2}(\w+)")
_LINE_MAGIC_RE = re.compile(r"^\s*[%!]")


def _source_to_text(source) -> str:
    if isinstance(source, list):
        return "".join(source)
    if isinstance(source, str):
        return source
    return ""


def _classify(cell_type: str, text: str) -> tuple[str, str]:
    """Return (bucket, body) for a cell, stripping a recognised whole-cell magic."""
    if cell_type == "markdown":
        return "md", text
    if cell_type != "code":
        return "", ""  # raw / unknown -> skip

    stripped = text.lstrip("\n")
    m = _MAGIC_RE.match(stripped)
    if m:
        name = m.group(1).lower()
        bucket = MAGIC_TO_BUCKET.get(name)
        if bucket:
            # Drop the magic line itself; keep the rest of the cell body.
            first_nl = stripped.find("\n")
            body = stripped[first_nl + 1:] if first_nl != -1 else ""
            return bucket, body
    return "py", text


def _sanitise_py(text: str) -> str:
    """Comment out inline line-magics / shell escapes so tree-sitter parses cleanly."""
    out = []
    for line in text.splitlines():
        if _LINE_MAGIC_RE.match(line):
            out.append("#nb> " + line)
        else:
            out.append(line)
    return "\n".join(out)


def convert_notebook(nb_path: Path, root: Path, outdir: Path | None) -> dict:
    try:
        nb = json.loads(nb_path.read_text(encoding="utf-8", errors="ignore"))
    except (json.JSONDecodeError, OSError) as exc:
        return {"notebook": str(nb_path), "error": str(exc), "written": []}

    cells = nb.get("cells")
    if not isinstance(cells, list):
        return {"notebook": str(nb_path), "error": "not a notebook (no cells)", "written": []}

    try:
        rel = nb_path.relative_to(root)
    except ValueError:
        rel = nb_path.name

    buckets: dict[str, list[str]] = {}
    counts: dict[str, int] = {}
    for i, cell in enumerate(cells):
        if not isinstance(cell, dict):
            continue
        text = _source_to_text(cell.get("source", ""))
        if not text.strip():
            continue
        bucket, body = _classify(cell.get("cell_type", ""), text)
        if not bucket or not body.strip():
            continue
        if bucket == "py":
            body = _sanitise_py(body)
        marker = COMMENT[bucket].format(f"%% cell {i} [{cell.get('cell_type', '?')}]")
        buckets.setdefault(bucket, []).append(f"{marker}\n{body.rstrip()}\n")
        counts[bucket] = counts.get(bucket, 0) + 1

    if outdir is not None:
        base = (outdir / rel)
        base.parent.mkdir(parents=True, exist_ok=True)
    else:
        base = nb_path

    written = []
    for bucket, chunks in buckets.items():
        ext = BUCKET_EXT[bucket]
        sidecar = base.with_name(f"{nb_path.stem}.ipynb.{ext}")
        header = COMMENT[bucket].format(f"Generated by ipynb-graphify from {rel} — do not edit.")
        sidecar.write_text(header + "\n\n" + "\n".join(chunks), encoding="utf-8")
        written.append(str(sidecar))

    return {"notebook": str(nb_path), "cells": len(cells), "counts": counts, "written": written}


def find_notebooks(root: Path):
    for p in root.rglob("*.ipynb"):
        if any(part in IGNORE_DIRS for part in p.parts):
            continue
        # Skip our own sidecars if a previous run named anything *.ipynb.*
        if p.name.count(".ipynb.") or p.suffixes[-2:] == [".ipynb", ".py"]:
            continue
        yield p


def clean(root: Path) -> list[str]:
    removed = []
    for ext in BUCKET_EXT.values():
        for p in root.rglob(f"*.ipynb.{ext}"):
            if any(part in IGNORE_DIRS for part in p.parts):
                continue
            try:
                p.unlink()
                removed.append(str(p))
            except OSError:
                pass
    return removed


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Split .ipynb notebooks into graphify-friendly sidecars.")
    ap.add_argument("path", nargs="?", default=".", help="File or directory to scan (default: cwd).")
    ap.add_argument("--outdir", default=None,
                    help="Mirror sidecars under this dir instead of writing next to each notebook.")
    ap.add_argument("--clean", action="store_true",
                    help="Remove previously generated *.ipynb.<ext> sidecars under PATH and exit.")
    args = ap.parse_args(argv)

    root = Path(args.path).resolve()
    if not root.exists():
        print(json.dumps({"error": f"path not found: {root}"}))
        return 1

    if args.clean:
        base = root if root.is_dir() else root.parent
        removed = clean(base)
        print(json.dumps({"cleaned": len(removed), "files": removed}, indent=2))
        return 0

    outdir = Path(args.outdir).resolve() if args.outdir else None
    scan_root = root if root.is_dir() else root.parent
    notebooks = [root] if root.is_file() and root.suffix == ".ipynb" else list(find_notebooks(root))

    results = [convert_notebook(nb, scan_root, outdir) for nb in notebooks]
    written = [w for r in results for w in r.get("written", [])]
    errors = [r for r in results if r.get("error")]

    summary = {
        "notebooks": len(notebooks),
        "sidecars_written": len(written),
        "errors": [{"notebook": e["notebook"], "error": e["error"]} for e in errors],
        "results": results,
    }
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
